[package]
name = "proto-types"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.1.5"
forward_ref = "1"
schemars = "0.8.3"
serde = { version = "1.0.103", default-features = false, features = [
    "derive",
    "alloc",
] }
thiserror = "1.0.13"
bech32 = "0.9.1"
lazy_static = "1.4.0"
regex = "1.7.1"

[dev-dependencies]
serde_json = "1.0.93"
