[package]
name = "trees"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.13"
sha2 = "0.10.6"
integer-encoding = "3.0.4"
database = { path = "../database" }

[dev-dependencies]
hex = "0.4.3"
